[project]
name = "rag-pdf-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "inngest>=0.5.19",
    "llama-index-core>=0.14.23",
    "llama-index-readers-file>=0.6.0",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "sentence-transformers>=5.6.1",
    "streamlit>=1.60.0",
    "unicorn>=2.1.4",
]
